# Generated by Django 4.1.3 on 2023-02-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
