# Generated by Django 4.1.3 on 2023-02-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_author_post_remove_tag_post_posts_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
